### ISSUE TITLE
mocap data glitch !

### ISSUE THREAD

**Issue by kotaxyz** [Qaanaaq/Face_Landmark_Link#1]
hello , thanks alot for this awesome tool , i have a question why the mocap data glitch alot , i have tested it on different tracks and imported the csv data in different apps but the same issue occurs
also i noticed that the keyframes down are empty in some places and alot in other places i dont think this is normal 

![Screenshot (53)](https://github.com/Qaanaaq/Face_Landmark_Link/assets/105466290/29d73a7e-2a3a-406d-b66e-a78baace65d5)

https://github.com/Qaanaaq/Face_Landmark_Link/assets/105466290/0bd45c95-d50e-45b5-8441-f9563125d3b3

**Comment by Qaanaaq** [comment]
Its issue with the framerate. Project framerate, importframerate and videoframerate all must be the same. Right now Face-it does not support custom framerate, but the next release will.

**Comment by zhudoudou159** [comment]
![E8T~I0WB5JZXQC1Y(IXM3I0](https://github.com/Qaanaaq/Face_Landmark_Link/assets/139295342/11be5a76-5db9-4827-b3a0-2e3ef7316e82)
Hello, thanks for writing this plugin, but why am I getting an error after importing a video, and the table data for CVS is empty
