### ISSUE TITLE
An error is reported after importing a video

### ISSUE THREAD

**Issue by zhudoudou159** [Qaanaaq/Face_Landmark_Link#4]
Hello, thanks for writing this plugin, but why am I getting an error after importing a video, and the table data for CVS is empty
![E8T~I0WB5JZXQC1Y(IXM3I0](https://github.com/Qaanaaq/Face_Landmark_Link/assets/139295342/49b54111-fc12-4ec2-a5f0-60011156ecad)

**Comment by Qaanaaq** [comment]
Please doublecheck if you have the file "face_landmarker.task" in the directory. If you have it there, my other guess is python might have a problem with chinese characters in the filename. Perhas try to run the file program directly from a drive F:, not desktop

**Comment by zhudoudou159** [comment]
> 请仔细检查目录中是否有文件“face_landmarker.task”。如果你有它，我的另一个猜测是 python 可能文件名中的汉字有问题。Perhas 尝试直接从驱动器 F： 运行文件程序，而不是桌面

Thank you very much, after putting the plug-in into the f drive, it can be used normally
