### ISSUE TITLE
error message when running .exe file

### ISSUE THREAD

**Issue by mentsurfari** [Qaanaaq/Face_Landmark_Link#5]
Great video! I am trying to use Face_landmarker_link_v0.2 on my macbook running windows virtually with virtualbox. When I try to run the .exe file I get the following error. Any advice? Thanks in advance! 

C:\Users\j\Desktop\Face_Landmarker_Link_V0.2\Face_Landmarker_Link\Face_Landmarker_Link.exe
<Traceback (most recent call last):
File "Face_Landmarker_Link.py", line 1, in <module>
File "PyInstaller\loader\pyimode2_importers.py", line 385, in exec_module File "mediapipe\___init__.py", line 15, in <module>
File
"PyInstaller\loader\pyimode2_importers.py", line 385, in exec_module
File "mediapipe\python\__init__.py", line 17, in <module>
ImportError: DLL load failed while importing _framework_bindings: The specified module could not be found. [3636] Failed to execute script 'Face_Landmarker_Link' due to unhandled exception!

**Comment by Qaanaaq** [comment]
Hello, 
I am afraid this is due to using windows emulation.  If you install python and mediapipe on mac, then with pyinstaller you could realitively easily build yourself a mac version.
