### ISSUE TITLE
Face_Landmark_Link

### ISSUE THREAD

**Issue by genjon** [Qaanaaq/Face_Landmark_Link#6]
Downloaded and scanned. Trojan detected crypto minor worm. Not safe!

**Comment by Qaanaaq** [comment]
Can you confirm that you used the VirusTotal? I got one positive by Jiangmin, all others negative. Jiangmin seems to find a lot of false positives. Here vlc.exe is detected. https://www.reddit.com/r/antivirus/comments/gp7v18/virus_total_virus_in_vlc_jiangmin_antivirus_engine/
however you can easily build your own executable.
