### ISSUE TITLE
Head Rotation Switched

### ISSUE THREAD

**Issue by lealavive** [Qaanaaq/Face_Landmark_Link#8]
Hi, 
first of all thank you for the great tool!
Sadly when I use Face_Landmark_Link and put the .cvs file into blender via the faceit add-on, the head rotation is wrong. When the video footage shows turning from side to side, the character in blender is looking up and down instead. Any clue on why that is and if there is any way to fix that?

![image](https://github.com/user-attachments/assets/9eb77180-58d4-49fe-87bb-5fcbe774e92b)

**Comment by Qaanaaq** [comment]
Hi, I doublechecked, you are absolutely right, those two values are by my mistake exchanged.  I will correct it in a future release, until then just open the .csv file and in the column HEAD YAW and HEAD PITCH, flip the values. The columnnames must remain in the same order, but if you exchange the values in column, it will work.  Hope this helps.

**Comment by lealavive** [comment]
Thank you so much for the answer! It finally works!!
